### ISSUE TITLE
Transformer kVA Rating

### ISSUE THREAD

**Issue by leighannngo** [stephenkaplan/plantpredict-python#78]
**Issue:**
Cannot specify a transformer kVA rating with the SDK.  Below image shows where this is located in the UI.

**Impacts:**
If a user chooses to enable the MV transformer and disable the "match total inverter kVA", they'll need to use the UI to specify a transformer kVA.

**Solution:**
Create a "transformer kVA rating" input parameter that can be specified by the user and defaults to the inverter kVA when it isn't specified.

![image](https://user-images.githubusercontent.com/53441041/62476068-2c9e7580-b75b-11e9-9231-d0093deed7c9.png)

**Comment by stephenkaplan** [comment]
should fix "creation project and prediction from scratch" example usage

**Comment by stephenkaplan** [comment]
this can't be implemented until completing https://github.com/stephenkaplan/plantpredict-python/issues/77

**Comment by stephenkaplan** [comment]
It turns out that the "base kVA on cooling temp" checkbox is actually a separate endpoint that needs to be called. I will do the following:

1. default "use_cooling_temp" to True, which is actually at the block level
2. use that value to determine if the inverter kVa calculation endpoint should be called at the inverter level
3. create a method from the inverter kVa endpoint
